### ISSUE TITLE
The solution to 2.84 seems to have a problem

### ISSUE THREAD

**Issue by littlecoke** [DreamAndDead/CSAPP-3e-Solutions#1]
I think you should not simply judge ux uy by comparing sx==sy. I think maybe the link is a proper answer.
https://github.com/mofaph/csapp/blob/master/exercise/ex2-83.c

**Comment by DreamAndDead** [comment]
I think we get the same goal with different expressions.

**Comment by zagortenay333** [comment]
This solution doesn't handle zeros. x = 000..00 and y = 100..00

**Comment by DreamAndDead** [comment]
@zagortenay333 did you mean +0 and -0?

This function named `float_le`, less or equal, so `float_le(+0, -0)` should return true here.

**Comment by zagortenay333** [comment]
Yes, but it won't return true when x=+0 and y=-0 since `sx != sy` and `sx > sy` is false.

**Comment by zagortenay333** [comment]
```c
    return
        !(ux<<1 || uy<<1) ||          /* both zero         */
        (sx > sy) ||                  /* x < 0 and y >= 0  */
        (!sx && !sy && ux <= uy) ||   /* x >= 0 and y >= 0 */
        (sx && sx && ux >= uy);       /* x < 0 and y < 0   */
```

**Comment by DreamAndDead** [comment]
thanks @littlecoke @zagortenay333 , how do you think https://github.com/DreamAndDead/CSAPP-3e-Solutions/commit/9d75393b07f17ea2a36b9753af5345d4eace4110

**Comment by 1036-ce** [comment]
Thank you!!

**Comment by sci-42ver** [comment]
maybe need use 
```c++
assert(float_le(-0.0, +0.0));
assert(float_le(+0.0, -0.0));
``` 
to generate negative zero known from [this](https://stackoverflow.com/questions/13767744/detecting-and-adjusting-for-negative-zero).

maybe also can use `return sx == sy ? (sx == 0 ? ux <= uy : ux >= uy) : sx > sy ? sx > sy : ux+uy==ux-uy && ux+uy==uy-ux;` to test which is inspired by above https://github.com/mofaph/csapp/blob/master/exercise/ex2-83.c

**Comment by paradox181** [comment]
我已收到您的邮件

**Comment by STEVENTAN100** [comment]
I think your answer isn't correct because it is prohibited to used Relative comparison operators(<, >, <= and >=) or any conditions(?:)

**Comment by paradox181** [comment]
我已收到您的邮件

**Comment by STEVENTAN100** [comment]
I think this will be a preferable answer without using relative operators:
```c
void float_le(float x, float y)
{
    unsigned ux = f2u(x);
    unsigned uy = f2u(y);

    unsigned sx = ux >> 31;
    unsigned sy = uy >> 31;

    unsigned uxt = ux << 1;          // true ux
    unsigned uyt = uy << 1;          // true uy
    unsigned st = (uxt - uyt) >> 31; // uxt-uyt sign bit

    printf("%u ", (uxt == 0 & uyt == 0) | /* both zeros */
                      ((sx ^ sy) & sx) |  /* x,y's sign bit is different */
                      (ux == uy) |        /* equal situation */
                      (!(sx ^ sy) & (st ^ sx)));
    /* sx,sy have same sign bits, then st,sx have different sign bits*/
}
```

**Comment by matthewevans1** [comment]
int float_le(float x, float y)
﻿{
﻿    unsigned ux = f2u(x);
﻿    unsigned uy = f2u(y);
﻿
﻿    /* Get the sign bits */
﻿    unsigned sx = ux >> 31;
﻿    unsigned sy = uy >> 31;
﻿    /* Give return an expression using only ux, uy, sx, and sy */
﻿    return (ux << 1 == 0 && uy << 1 == 0) ||
﻿        (ux <= uy) ? (sy == 0 || ux == uy) : sx == 1;
﻿}
﻿
﻿int main()
﻿{
﻿    for (float x = -10000; x < 10001; x++) {
﻿        for (float y = -10000; y < 10001; y++) {
﻿            if(float_le(x, y) != (x <= y))
﻿                printf("i=%f,j=%f\n", x, y);
﻿        }
﻿    }
﻿
﻿    assert(float_le(-0, +0));
﻿    assert(float_le(+0, -0));
﻿    assert(float_le(0, 3));
﻿    assert(float_le(-4, -0));
﻿    assert(float_le(-4, 4));
﻿
﻿    return 0;
﻿}

**Comment by matthewevans1** [comment]
`int float_le(float x, float y)
﻿{
﻿    unsigned ux = f2u(x);
﻿    unsigned uy = f2u(y);
﻿
﻿    /* Get the sign bits */
﻿    unsigned sx = ux >> 31;
﻿    unsigned sy = uy >> 31;
﻿    /* Give return an expression using only ux, uy, sx, and sy */
﻿    return (ux << 1 == 0 && uy << 1 == 0) ||
﻿        (ux <= uy) ? (sy == 0 || ux == uy) : sx == 1;
﻿}
﻿
﻿int main()
﻿{
﻿    for (float x = -10000; x < 10001; x++) {
﻿        for (float y = -10000; y < 10001; y++) {
﻿            if(float_le(x, y) != (x <= y))
﻿                printf("i=%f,j=%f\n", x, y);
﻿        }
﻿    }
﻿
﻿    assert(float_le(-0, +0));
﻿    assert(float_le(+0, -0));
﻿    assert(float_le(0, 3));
﻿    assert(float_le(-4, -0));
﻿    assert(float_le(-4, 4));
﻿
﻿    return 0;
﻿}`

**Comment by matthewevans1** [comment]
```c
int float_le(float x, float y)
{
    unsigned ux = f2u(x);
    unsigned uy = f2u(y);

    /* Get the sign bits */
    unsigned sx = ux >> 31;
    unsigned sy = uy >> 31;
    /* Give return an expression using only ux, uy, sx, and sy */
    return (ux << 1 == 0 && uy << 1 == 0) ||
        (ux <= uy) ? (sy == 0 || ux == uy) : sx == 1;
}

int main()
{
    for (float x = -10000; x < 10001; x++) {
        for (float y = -10000; y < 10001; y++) {
            if(float_le(x, y) != (x <= y))
                printf("i=%f,j=%f\n", x, y);
        }
    }

    assert(float_le(-0, +0));
    assert(float_le(+0, -0));
    assert(float_le(0, 3));
    assert(float_le(-4, -0));
    assert(float_le(-4, 4));

    return 0;
}
```

**Comment by paradox181** [comment]
我已收到您的邮件
