### ISSUE TITLE
2.82 E is wrong

### ISSUE THREAD

**Issue by 1471765122** [DreamAndDead/CSAPP-3e-Solutions#10]
x = INT_MIN + 1
(x >> 2) << 2 = 10000000000000000000000000000000
while x = 10000000000000000000000000000001
so E is wrong

**Comment by DreamAndDead** [comment]
A good example.

if x = INT_MIN + 1,
(x >> 2) << 2 = INT_MIN,

    INT_MIN < INT_MIN + 1
    ((x >> 2) << 2) <= x

It looks expression E is right :)

**Comment by 1471765122** [comment]
Oh! The operator is <= .
Your answer is right.
Thank you.
