### ISSUE TITLE
The solution to 9.16 seems to have a problem

### ISSUE THREAD

**Issue by upupming** [DreamAndDead/CSAPP-3e-Solutions#4]
[This](http://csapp.cs.cmu.edu/3e/errata.html) is Errata for CS:APP3e and its Instructors Manual, it says:

> The answer for the first case should be 16 bytes, rather than 20 bytes. 

And [this](https://github.com/upupming/CSAPP/blob/master/chapter9/9.16.md) is my own solution.

**Comment by DreamAndDead** [comment]
Yes, you are right! I will correct it : )

**Comment by DreamAndDead** [comment]
https://github.com/DreamAndDead/CSAPP-3e-Solutions/commit/6857c20378212684fba3e11e1dfa243ce6140135#diff-9a271a2fc70cc322767a94d7361deeb4
