### ISSUE TITLE
Problem 3.66

### ISSUE THREAD

**Issue by gonglinyuan** [DreamAndDead/CSAPP-3e-Solutions#5]
> leaq 1(,%rdi,4), %r8        # t1 = n*4

Why not n\*4+1 ?

My answer is 
NR(n) = n\*3
NC(n) = n\*4+1

**Comment by DreamAndDead** [comment]
Brilliant!

I assumed that [array in test code](https://github.com/DreamAndDead/CSAPP-3e-Solutions/commit/312627fa0a2bc7533f2330d842b25b5e924bbe40#diff-8636ed393c67e80dd316f96a07cdebe0L10) would be occupied by random numbers. Actually all elements in array are always zeros every time we run it, so the test code figures out nothing :(
